#!/bin/bash
# =============================================================================
#  lib/udev.sh
#  Creates a udev rule so the CAT serial port always appears at a
#  predictable path (/dev/hamradiocat) regardless of plug order.
#
#  Uses HB_UDEV_VENDOR and HB_UDEV_PRODUCT set during radio selection
#  in install.sh, and HB_CAT_DEVICE_ALIAS from config.sh.
# =============================================================================

hb_install_udev() {
    hb_step "Creating udev rule for stable CAT port name"

    cat > "$HB_UDEV_RULE_FILE" << EOF
# HamBridge — stable CAT serial port alias
# Generated by hambridge installer on $(date)
# Vendor: $HB_UDEV_VENDOR  Product: $HB_UDEV_PRODUCT
# Edit HB_UDEV_VENDOR / HB_UDEV_PRODUCT in install.sh to change the target device
SUBSYSTEM=="tty", ATTRS{idVendor}=="$HB_UDEV_VENDOR", ATTRS{idProduct}=="$HB_UDEV_PRODUCT", SYMLINK+="$HB_CAT_DEVICE_ALIAS"
EOF

    udevadm control --reload-rules
    udevadm trigger

    hb_success "udev rule written to $HB_UDEV_RULE_FILE"
    hb_info    "CAT port will appear as /dev/$HB_CAT_DEVICE_ALIAS"
}
