#!/bin/bash
# =============================================================================
#  lib/udev.sh
#  Creates udev rules so the CAT serial port always appears at a
#  predictable path (/dev/hambridge) regardless of plug order.
#
#  Both supported interfaces are covered so the installer asks no
#  questions about hardware — it works with either out of the box:
#    DR-891:          Silicon Labs CP210x  (vendor 10c4, product ea70)
#    Digirig Mobile:  FTDI FT232R          (vendor 0403, product 6001)
# =============================================================================

hb_install_udev() {
    hb_step "Creating udev rules for stable CAT port name"

    cat > "$HB_UDEV_RULE_FILE" << UDEV
# HamBridge — stable CAT serial port alias
# Generated by hambridge installer on $(date)
# Covers both DR-891 (CP210x) and Digirig Mobile (FTDI)

# DR-891 (Silicon Labs CP210x — FT-891 USB passthrough)
SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea70", SYMLINK+="hambridge"

# Digirig Mobile (FTDI FT232R — FT-747GX CAT cable)
SUBSYSTEM=="tty", ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6001", SYMLINK+="hambridge"
UDEV

    udevadm control --reload-rules
    udevadm trigger

    hb_success "udev rules written to $HB_UDEV_RULE_FILE"
    hb_info    "CAT port will appear as /dev/hambridge"
    hb_info    "Works with DR-891 and Digirig Mobile automatically"
}
